#case study 1


```{r}
library(tidyverse)
library(mice)
library(ggplot2)
library(stringr)
library(class)
library(caret)
library(ggthemes)
library(VIM)
library(lattice)
library(DMwR)
```

```{r}
beers = read.csv("Beers.csv")
breweries = read.csv("Breweries.csv")
head(beers)
head(breweries)
```


#question 1: how many breweries are present in each state?

```{r}
state_breweries <- breweries %>%
  group_by(State) %>%
  tally()
head(state_breweries)
state_breweries %>%
  ggplot(aes(x=State, y=n)) +
  geom_bar(stat = "identity")
```

#Merging Beer and Breweries data
```{r}
breweries1 <- breweries %>%
  left_join(beers, by = c("Brew_ID" = "Brewery_id"))
head(breweries1,6)
tail(breweries1,6)
```
#Missing Values
```{r}

#plot the NAs
breweries1_miss = aggr(breweries1, col=mdc(1:2), numbers=TRUE, sortVars=TRUE, labels=names(breweries1), cex.axis=.7, gap=3, ylab=c("Proportion of NAs","NA Pattern"))

breweries1_impute <- knnImputation(breweries1)

```
#Scatterplot of IBU Vs. ABV
```{r}
breweries1_impute %>% ggplot(aes(x=ABV,y=IBU)) + theme_fivethirtyeight() + geom_point()+geom_smooth(method=lm) + labs(x = "Alcohol By Volume (ABV)",y = "International Bitterness Unit (IBU)", title = "Relationship Between ABV and IBU")

cor(breweries1_impute$ABV,breweries1_impute$IBU)

# Judging by the scatterplot and the regression line there seems to be a positive correlation between ABV and IBU.  So that means there is a positive relationship betwen ABV and IBU so as ABV increases, so does IBU. 
```
#Knn Part 1: Configuring the data to identify which Style is IPA or Ale

```{r}
breweriesKnn <- breweries1_impute
for (i in 1: nlevels(breweriesKnn$Style))
{
  if (grepl("IPA",levels(breweriesKnn$Style)[i]) == TRUE)
  {
    levels(breweriesKnn$Style)[i] = "IPA"
  }
  
}
for (j in 1: nlevels(breweriesKnn$Style))
{
  if (grepl("Ale",levels(breweriesKnn$Style)[j]) == TRUE)
  {
    levels(breweriesKnn$Style)[j] = "Ale"
  }
  
}
for (d in 1: nlevels(breweriesKnn$Style))
{
  if (grepl("American Blonde Ale",levels(breweriesKnn$Style)[d]) == TRUE)
  {
    levels(breweriesKnn$Style)[d] = "Ale"
  }
  if (grepl("English Dark Mild Ale",levels(breweriesKnn$Style)[d]) == TRUE)
  {
    levels(breweriesKnn$Style)[d] = "Ale"
  }
  if (grepl("Scottish Ale",levels(breweriesKnn$Style)[d]) == TRUE)
  {
    levels(breweriesKnn$Style)[d] = "Ale"
  }
  if (grepl("Belgian Pale Ale",levels(breweriesKnn$Style)[d]) == TRUE)
  {
    levels(breweriesKnn$Style)[d] = "Ale"
  }
  if (grepl("Belgian Strong Pale Ale",levels(breweriesKnn$Style)[d]) == TRUE)
  {
    levels(breweriesKnn$Style)[d] = "Ale"
  }
  if (grepl("American Dark Wheat Ale",levels(breweriesKnn$Style)[d]) == TRUE)
  {
    levels(breweriesKnn$Style)[d] = "Ale"
  }
  if (grepl("English Pale Mild Ale",levels(breweriesKnn$Style)[d]) == TRUE)
  {
    levels(breweriesKnn$Style)[d] = "Ale"
  }
  if (grepl("American Wild Ale",levels(breweriesKnn$Style)[d]) == TRUE)
  {
    levels(breweriesKnn$Style)[d] = "Ale"
  }
  
}
```

#Knn Part 2: Using Knn model to predict Style of Beer
```{r}
breweriesKnn<-breweriesKnn %>% filter(Style=="IPA"|Style=="Ale")%>% droplevels()
set.seed(6)
splitPerc = .7
trainIndices = sample(1:dim(breweriesKnn)[1],round(splitPerc * dim(breweriesKnn)[1]))
train = breweriesKnn[trainIndices,]
test = breweriesKnn[-trainIndices,]
accs = data.frame(accuracy = numeric(100), k = numeric(100))

for(i in 1:100)
{
styles = knn.cv(breweriesKnn[,c(6,7)],breweriesKnn$Style, prob = TRUE, k = i)
  table(breweriesKnn$Style,styles)
  CM = confusionMatrix(table(breweriesKnn$Style,styles))
  accs$accuracy[i] = CM$overall[1]
  accs$k[i] = i
}

plot(accs$k,accs$accuracy, type = "l", xlab = "k")
accu = accs$accuracy
max(accu)



```


```{r}
iterations = 500
numks = 100

masterAcc = matrix(nrow = iterations, ncol = numks)

for(j in 1:iterations)
{
accs = data.frame(accuracy = numeric(100), k = numeric(100))
trainIndices = sample(1:dim(breweriesKnn)[1],round(splitPerc * dim(breweriesKnn)[1]))
train = breweriesKnn[trainIndices,]
test = breweriesKnn[-trainIndices,]
for(i in 1:numks)
{
  styles = knn(train[,c(6,7)],test[,c(6,7)],train$Style, prob = TRUE, k = i)
  table(styles,test$Styles)
  CM = confusionMatrix(table(styles,test$Styles))
  masterAcc[j,i] = CM$overall[1]
}

}

MeanAcc = colMeans(masterAcc)

plot(seq(1,numks,1),MeanAcc, type = "l")
```


```{r}
